version: '2.3'
services:
  vault-svc:
    image: "vault:${SVC_VAULT_VERSION:-1.12.1}"
    healthcheck:
      test: wget http://127.0.0.1:8200/v1/sys/health > /dev/null 2>&1
      interval: 2s
      timeout: 10s
      retries: 5
    cap_add:
    - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - VAULT_TOKEN=${VAULT_DEV_ROOT_TOKEN_ID}
      - VPC_PROXY
      - VAULT_ADDR="http://0.0.0.0:8200"
  vault-tester:
    build: ./
    image: "vault-tester"
    links:
      - vault-svc
    depends_on:
      vault-svc:
        condition: service_healthy
    volumes:
      - .:/app
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID
      - VAULT_ADDR
      - VPC_PROXY
      - BUILDKITE_PLUGIN_VAULT_SECRETS_SERVER
      - BUILDKITE_PLUGIN_VAULT_SECRETS_DUMP_ENV=true
      - BUILDKITE_PLUGIN_VAULT_SECRETS_AUTH_TOKEN
    entrypoint:
      - ""
    command:
      /app/.buildkite/steps/test_integration.sh
