version: '2.2'
services:
  tests:
    image: buildkite/plugin-tester:v4.2.0
    volumes:
      - .:/plugin

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'vault-secrets']
    volumes:
      - ".:/plugin"

  shellcheck:
    image: koalaman/shellcheck:latest
    command: -x lib/shared.bash hooks/environment hooks/pre-exit
    working_dir: /plugin
    volumes:
      - ".:/plugin"
