name: "Vault Secrets"
description: "Expose build secrets stored in Vault to your jobs"
author: "@mikeknox, @buildkite-plugins"
public: true
requirements:
  - curl
  - bash
  - vault
configuration:
  properties:
    server:
      type: string
    auth-method:
      type: string
    role-id:
      type: string
    secret-id:
      type: string
  required:
    - server
  additionalProperties: false

