name: "Vault Secrets"
description: "Expose build secrets stored in Vault to your jobs"
author: "@mikeknox, @buildkite-plugins"
public: true
requirements:
  - curl
  - bash
  - vault
configuration:
  properties:
    path:
      type: string
    server:
      type: string
    auth:
      type: object
      properties:
        method:
          enum:
            - 'approle'
            - ''
        role-id:
          type: string
        secret-env:
          type: string
    secrets:
      type: array
  additionalProperties: false
  required: [ auth ]
    

