env:
  BK_QUEUE_NAME: "testqueue" # probably don't need this
  TESTER_VAULT_VERSION: "1.11.2" # this probably needs to get bumped over time
  SVC_VAULT_VERSION: "1.11.2" # this probably needs to get bumped over time
  VAULT_ADDR: "http://vault-svc:8200"
  BUILDKITE_PIPELINE_SLUG: "my_pipeline"
  DUMP_ENV: "true"
  VAULT_DEV_ROOT_TOKEN_ID: "88F4384B-98E9-4AE3-B00C-F55678F89080"
steps:
  - label: ":bat: :test_tube: Run tests"
    plugins:
      - shellcheck#v1.3.0:
          files: lib/*.bash
      - plugin-linter#v2.0.0:
          id: vault-secrets
      - docker-compose#v4.5.0:
          run: tests
          
  - label: ":vault: :test_tube: Integration Tests"
    command: bash /app/.buildkite/steps/test_envvar.sh
    plugins:
      docker-compose#v4.5.0:
        config:
          - docker-compose-integration.yml
        run: vault-tester
        env:
          - VAULT_ADDR
          - BUILDKITE_PLUGIN_VAULT_SECRETS_SERVER=${VAULT_ADDR}
          - BUILDKITE_PIPELINE_SLUG
          - BUILDKITE_PLUGIN_VAULT_SECRETS_DUMP_ENV=${DUMP_ENV}
          - VAULT_DEV_ROOT_TOKEN_ID
          - BUILDKITE_PLUGIN_VAULT_SECRETS_AUTH_TOKEN=${VAULT_DEV_ROOT_TOKEN_ID}
          - SVC_VAULT_VERSION
          - TESTER_VAULT_VERSION